apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels: 
    app: segundo-pod # para o serviço saber qual pod se comunicar
spec:
  containers:
    - name: container-pod-1
      image: nginx:latest
      ports:
        - containerPort: 80