apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod # atrelado ao pod que tiver a labels com 'app: segundo-pod'
  ports:
    - port: 9000 # em qual porta o meu servido está escutando
      targetPort: 80 # e em qual ele vai despachar a requisição vinda pela a porta 9000
