apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset # metadata do meu replica-set
spec:
  template:
    metadata: # metadata dentro do meu replica-set
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticia
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  
  replicas: 3
  selector:
    matchLabels: # para quando um pod falhar o replicar saber qual metadata subir novamente
      app: portal-noticias
  
  